# DATA PREPROCESSING

## Importing the libraries

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [5]:
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, 4].values

## Splitting data into test and train

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# USING PANDAS AND NUMPY

## Getting first 5 and last 5 colounm

In [11]:
dataset.head(5)
#dataset.tail(5)

User ID  Gender  Age  EstimatedSalary  Purchased
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

## Getting shape of datset

In [9]:
dataset.shape

(400, 5)

## Get description of dataset

In [12]:
dataset.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

## Print rows with age 22

In [22]:
dataset.loc[dataset['Age'] == 22]

User ID  Gender  Age  EstimatedSalary  Purchased
58   15642885    Male   22            18000          0
68   15577178  Female   22            63000          0
77   15774179  Female   22            27000          0
90   15684801    Male   22            81000          0
166  15762228  Female   22            55000          0

# USING NUMPY

## Creating array usng numpy

In [29]:
array1 = np.array([1, 2, 3, 4, 5])
print(array1)

array2 = np.array([[[1, 2, 3], [4, 5, 6]]])
print(array2)

[1 2 3 4 5]
[[[1 2 3]
  [4 5 6]]]


## Dimenison of array

In [31]:
print(array1.ndim)
print(array2.ndim)

1
3


## Creating 2x3 array with all zeroes

In [34]:
array3 = np.zeros((2,3))
print(array3)

[[0. 0. 0.]
 [0. 0. 0.]]


## Print the shape of an array

In [36]:
array3.shape

(2, 3)

## Reshaping array

In [38]:
array3.reshape(1,6)

array([[0., 0., 0., 0., 0., 0.]])

## Creating random array

In [46]:
array4 = np.random.random((3,3))
print(array4)

## rounding of elements of an array

In [42]:
np.around(array4)

array([[1., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
array5 = np.array([3, 2, 0, 1])
np.sort(array5)

array([0, 1, 2, 3])

## arithematic operations

In [52]:
a = np.array([10, 11, 12, 13, 14, 15])
b = np.array([20, 21, 22, 23, 24, 25])

new1 = np.add(a, b)
new2 = np.subtract(a, b)
print(new1)
print(new2)
print(np.log2(a))
product = np.prod(a)
print(product)

[30 32 34 36 38 40]
[-10 -10 -10 -10 -10 -10]
[3.32192809 3.45943162 3.5849625  3.70043972 3.80735492 3.9068906 ]
3603600
